name: Cmake

on:
  workflow_call:

env:
  BUILD_TYPE_RELEASE: Release
  CLANG_14: clang++-14

jobs:
  ubuntu-clang-14-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update
      - run: sudo apt-get install -y ${{env.CLANG_14}}
      - run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=/bin/${{env.CLANG_14}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE_RELEASE}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE_RELEASE}} --target example
      - run: ${{github.workspace}}/build/bin/example
